name: optibot

services:
  - name: api
    http_port: 8000
    source_dir: .
    dockerfile_path: Dockerfile
    instance_size_slug: basic-xxs
    envs:
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}
      - key: PYTHONUNBUFFERED
        value: '1'
    run_command: python -m assistant.server
    mounts:
      - source: chroma-storage
        destination: /mnt/chroma_storage

jobs:
  - name: daily-scraper
    source_dir: .
    dockerfile_path: Dockerfile.scraper
    schedule: '0 3 * * *' # run daily 3AM UTC
    instance_size_slug: basic-xxs
    envs:
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}
    mounts:
      - source: chroma-storage
        destination: /mnt/chroma_storage

volumes:
  - name: chroma-storage
    size_gigabytes: 2
